# Generated by Django 5.0.6 on 2024-07-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('professor', models.TextField(max_length=255)),
                ('material', models.TextField(max_length=255)),
                ('sala', models.TextField(max_length=50)),
            ],
        ),
    ]
