# Generated by Django 5.0.6 on 2024-07-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle_equip', '0002_reservas_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('material', models.TextField(max_length=255)),
                ('data', models.DateField()),
                ('sala', models.TextField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Reservas',
        ),
    ]
