# Generated by Django 5.0.6 on 2024-07-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle_equip', '0003_reserva_delete_reservas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='sala',
            field=models.TextField(max_length=100),
        ),
    ]
